amcl:
    ros__parameters:
        use_sim_time: True
        min_particles: 100
        max_particles: 5000
        transform_tolerance: 0.2
        update_min_d: 0.1
        update_min_a: 0.2

controller_server:
    ros__parameters:
        use_sim_time: True
        controller_frequency: 20.0
        min_x_velocity_threshold: 0.001
        min_y_velocity_threshold: 0.001
        min_theta_velocity_threshold: 0.001
        controller_plugins: ['FollowPath']
        FollowPath:
            plugin: 'nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController'
            desired_linear_vel: 0.2
            max_linear_accel: 0.5
            max_angular_vel: 1.0
            max_angular_accel: 2.0

planner_server:
    ros__parameters:
        use_sim_time: True
        planner_plugins: ['GridBased']
        GridBased:
            plugin: 'nav2_navfn_planner/NavfnPlanner'
            tolerance: 0.5
            use_astar: False

global_costmap:
    global_costmap:
        ros__parameters:
            use_sim_time: True
            update_frequency: 1.0
            publish_frequency: 1.0
            global_frame: 'map'
            robot_base_frame: 'base_link'
            resolution: 0.05
            plugins: ['static_layer', 'obstacle_layer', 'inflation_layer']
            static_layer:
                plugin: 'nav2_costmap_2d::StaticLayer'
                map_subscribe_topic: '/map'
            obstacle_layer:
                plugin: 'nav2_costmap_2d::ObstacleLayer'
                observation_sources: 'scan'
                scan:
                    topic: '/scan'
                    max_obstacle_height: 2.0
                    clearing: True
                    marking: True
            inflation_layer:
                plugin: 'nav2_costmap_2d::InflationLayer'
                inflation_radius: 0.3

local_costmap:
    local_costmap:
        ros__parameters:
            use_sim_time: True
            update_frequency: 5.0
            publish_frequency: 2.0
            global_frame: 'odom'
            robot_base_frame: 'base_link'
            resolution: 0.05
            rolling_window: True
            width: 3.0
            height: 3.0
            plugins: ['obstacle_layer', 'inflation_layer']
            obstacle_layer:
                plugin: 'nav2_costmap_2d::ObstacleLayer'
                observation_sources: 'scan'
                scan:
                    topic: '/scan'
                    max_obstacle_height: 2.0
                    clearing: True
                    marking: True
            inflation_layer:
                plugin: 'nav2_costmap_2d::InflationLayer'
                inflation_radius: 0.3
