async_slam_toolbox_node:
    ros__parameters:
        use_sim_time: True
        odom_frame: 'odom'
        map_frame: 'map'
        base_frame: 'base_footprint'
        transform_publish_period: 0.02 # 50 Hz
        map_update_interval: 5.0
        resolution: 0.05
        max_laser_range: 3.5 # Match your lidar
        minimum_travel_distance: 0.05
        minimum_travel_heading: 0.087 # ~5 degrees
        scan_topic: '/scan'
        mode: 'mapping' # or "localization" if using a pre-built map
